# Generated by Django 4.1.2 on 2022-10-21 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('freekm', models.CharField(max_length=100)),
                ('dbp', models.FloatField(max_length=10)),
                ('dap', models.FloatField(max_length=10)),
                ('tmf', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.PositiveBigIntegerField()),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('distance', models.FloatField(blank=True, null=True)),
                ('total', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.priceoption')),
            ],
        ),
    ]
